# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
