# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160109_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='begin',
            field=models.TimeField(),
        ),
    ]
