# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20160111_1414'),
    ]

    operations = [
       
    ]
