# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 14:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20160111_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
