# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeland', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='auser',
            name='userid',
        ),
        migrations.AddField(
            model_name='auser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
